[package]
name = "util"
version = "0.0.0"
authors = ["Edgar Geier <egeier@rhrk.uni-kl.de>"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bytes = "1"
cfg-if = "1"
memmap = "0.7"
derive = { path = "../derive" }
egui = { version = "0.13.1", optional = true }
