[package]
name = "physics"
version = "0.0.0"
authors = ["Edgar Geier <egeier@rhrk.uni-kl.de>"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bitflags = "1.3.2"
rapier3d = "0.11.0"
nalgebra = "0.29.0"
protocol = { path = "../protocol" }
