[package]
name = "generator-spirv"
version = "0.0.0"
authors = ["Edgar Geier <egeier@rhrk.uni-kl.de>"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[build-dependencies]
spirv-builder = { git = "https://github.com/wosim-net/rust-gpu.git" }
