name: CI

on:
    push:
        branches: ['main']
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [16]

        steps:
            - uses: actions/checkout@v2

            - name: Install Vulkan SDK and dependencies (Ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: |
                  wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
                  sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
                  sudo apt update
                  sudo apt install vulkan-sdk libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev

            - name: Install Vulkan SDK (Windows)
              if: matrix.os == 'windows-latest'
              run: |
                  choco install vulkan-sdk --version=1.2.162.1
                  echo "VULKAN_SDK=C:\VulkanSDK\1.2.162.1" >> $GITHUB_ENV
              shell: bash

            - name: Install MoltenVK (macOS)
              if: matrix.os == 'macos-latest'
              run: brew install molten-vk

            - name: Rust toolchain
              run: rustup show

            - name: Rust cache
              uses: Swatinem/rust-cache@v1
              
            - name: Build
              run: cargo build --workspace --verbose
            - name: Format
              run: cargo fmt --all --verbose
            - name: Lint
              run: cargo clippy --workspace --verbose -- -D warnings
            - name: Test
              run: cargo test --workspace --verbose
